# Basic Connection Settings
spring.application.name=INTERLINK

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?prepareThreshold=0&ApplicationName=Kavindulal
spring.datasource.username=postgres.zyvhemluugmpciqnpygo
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP (Supabase free tier safe)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=60000

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# OPENAI
openai.api.key=${OPENAI_API_KEY}

# SUPABASE
supabase.service.key=${SERVICE_KEY}
supabase.url=${SUPABASE_URL}

# Server
server.port=8080
spring.main.allow-bean-definition-overriding=true

# Security
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://zyvhemluugmpciqnpygo.supabase.co/auth/v1/.well-known/jwks.json